bitbucketURL : "test123",
applicationName : "spring_boot_basic",
dockerImageName : "testImage",
kubernateNamespace : "test",
secerts:
  properties1: "properties_values_1",
  properties2: "properties_values_2"