apiVersion: v1
kind: Service
metadata:
  name: test-basic-service
  namespace: test
spec:
  selector:
    app: test-basic-app
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-basic-deployment
  namespace: test
  labels:
    app: test-basic-app
    app.kubernetes.io/component: API
    spring-boot-version: 2.6.6
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-basic-app
  template:
    metadata:
      labels:
        app: test-basic-app
        app.kubernetes.io/component: API
        spring-boot-version: 2.6.6
    spec:
      containers:
        - name: test-basic-app
          image: fra.ocir.io/entercard/msp/proenv/curiosity01:test-test-basic-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: test-basic-configmap

          livenessProbe:
            httpGet:
              path: /basic/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30 #Default 10 number of seconds to wait until the probe is initiated after the container start.
            periodSeconds: 30 #Default 10 : Defines how often the probe performs the healthcheck, in seconds.
            timeoutSeconds: 5 #Default 1 : Determines after how much time the probe times out, in seconds
            successThreshold: 1 #Default 1 : The minimum number of consecutive healthcheck successes before the container is considered healthy after being unhealthy.
            failureThreshold: 3 #Default 3 :The maximum number of consecutive healthcheck failures before the container is considered unhealthy and being restarted.

          readinessProbe:
            httpGet:
              path: /basic/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30 #Default 0 : The number of seconds to wait until the probe is initiated after the container start.
            periodSeconds: 30 #Default 10 : Defines how often the probe performs the healthcheck, in seconds.
            timeoutSeconds: 5 #Default 1 : Determines after how much time the probe times out, in seconds
            successThreshold: 1 #Default 1 : The minimum number of consecutive healthcheck successes before the container is considered healthy after being unhealthy.
            failureThreshold: 3 #Default 3 : The maximum number of consecutive healthcheck failures before the container is considered unhealthy and being restarted.

      imagePullSecrets:
        - name: ocirsecret
